/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ImportantRouteImport } from './routes/important'
import { Route as UnitSlugRouteImport } from './routes/unit.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportantRoute = ImportantRouteImport.update({
  id: '/important',
  path: '/important',
  getParentRoute: () => rootRouteImport,
} as any)
const UnitSlugRoute = UnitSlugRouteImport.update({
  id: '/unit/$slug',
  path: '/unit/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/important': typeof ImportantRoute
  '/unit/$slug': typeof UnitSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/important': typeof ImportantRoute
  '/unit/$slug': typeof UnitSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/important': typeof ImportantRoute
  '/unit/$slug': typeof UnitSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/important' | '/unit/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/important' | '/unit/$slug'
  id: '__root__' | '/' | '/important' | '/unit/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImportantRoute: typeof ImportantRoute
  UnitSlugRoute: typeof UnitSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/important': {
      id: '/important'
      path: '/important'
      fullPath: '/important'
      preLoaderRoute: typeof ImportantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unit/$slug': {
      id: '/unit/$slug'
      path: '/unit/$slug'
      fullPath: '/unit/$slug'
      preLoaderRoute: typeof UnitSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImportantRoute: ImportantRoute,
  UnitSlugRoute: UnitSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
